version: "3"
services:
  algo_app:
    build: .
    volumes:
      - ./../model_inputs_outputs:/opt/model_inputs_outputs
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: tail -f /dev/null # keep the container running
